[language-server.godot-lsp]
command = "nc"
args = [
  "127.0.0.1",
  "6005",
]

[[language]]
name = "gdscript"
language-servers = ["godot-lsp"]

[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
